// Fax Form actions
export const SEND_FAX = 'SEND_FAX'
export const SEND_FAX_REQUEST = 'SEND_FAX_REQUEST'
export const SEND_FAX_FAILURE = 'SEND_FAX_FAILURE'
export const SEND_FAX_SUCCESS = 'SEND_FAX_SUCCESS'
export const WEB_SOCKET_CREATED_SUCCESS = 'WEB_SOCKET_CREATED_SUCCESS'
export const UPDATE_FAX_STATUS = 'UPDATE_FAX_STATUS'
export const SYNC_FAX = 'SYNC_FAX'
